include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - p4_sim
  - rtl_sim
  - bitfile
  - package
  - trigger_downstream

variables:
  OPEN_NIC_REPO_BRANCH: v1.2-dev-2021.2
  GIT_STRATEGY: clone

.common:
  image: wharf.es.net/ht/xilinx-tools-docker:21087-g4c4c1a59
  tags:
    - ht-docker
  before_script:
    - source /opt/Xilinx/Vivado/2021.2/settings64.sh
  variables:
    XILINXD_LICENSE_FILE: "2100@dmv.es.net"
    # Required to keep click python module happy
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
    GIT_SUBMODULE_STRATEGY: recursive

p4bm:
  stage: p4_sim
  extends: .common
  script:
    - make -C src/p4_app/p4/sim build sim-all
    - make -C examples/p4_simple/p4/sim sim-all
    - make -C examples/unsupported/p4_example/p4/sim build sim-all
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - src/p4_app/p4/sim
      - examples/p4_simple/p4/sim
      - examples/unsupported/p4_example/p4/sim
  needs: []

sim_p4_apps:
  stage: rtl_sim
  extends: .common
  script:
    - make -C src/p4_app/tests/regression
    - grep 'PASSED.*suites passing' src/p4_app/tests/regression/run_0/sim.log
    - make -C examples/unsupported/p4_example/tests/regression
    - grep 'PASSED.*suites passing' examples/unsupported/p4_example/tests/regression/run_0/sim.log
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    reports:
      junit:
        - src/p4_app/tests/regression/run_0/tests.xml
        - examples/unsupported/p4_example/tests/regression/run_0/tests.xml
    when: always
  timeout: 2h
  needs: []

sim_platform:
  stage: rtl_sim
  extends: .common
  script:
    - make -C src/smartnic_322mhz/tests/regression
    - grep 'PASSED.*suites passing' src/smartnic_322mhz/tests/regression/run_0/sim.log
    - make -C examples/unsupported/p2p/tests.smartnic_322mhz/regression
    - grep 'PASSED.*suites passing' examples/unsupported/p2p/tests.smartnic_322mhz/regression/run_0/sim.log
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    reports:
      junit:
        - src/smartnic_322mhz/tests/regression/run_0/tests.xml
        - examples/unsupported/p2p/tests.smartnic_322mhz/regression/run_0/tests.xml
    when: always
  timeout: 2h
  needs: []

build_p4_example:
  stage: bitfile
  extends: .common
  before_script:
    - source /opt/Xilinx/Vivado/2021.2/settings64.sh
  script:
    - make -C examples/unsupported/p4_example build BUILD_NAME=open-nic-ci
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - src
      - esnet-fpga-library
      - examples
      - open-nic-shell
    exclude:
      - .git/**
      - .git
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
    when: always
    expire_in: 2 weeks
  timeout: 8h
  needs: []

build_p2p_example:
  stage: bitfile
  extends: .common
  before_script:
    - source /opt/Xilinx/Vivado/2021.2/settings64.sh
  script:
    - make -C examples/unsupported/p2p build BUILD_NAME=open-nic-ci
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - src
      - esnet-fpga-library
      - examples
      - open-nic-shell
    exclude:
      - .git/**
      - .git
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
    when: always
    expire_in: 2 weeks
  timeout: 8h
  needs: []

build_p4_simple:
  stage: bitfile
  extends: .common
  before_script:
    - source /opt/Xilinx/Vivado/2021.2/settings64.sh
  script:
    - make -C examples/p4_simple build BUILD_NAME=open-nic-ci
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - src
      - esnet-fpga-library
      - examples
      - open-nic-shell
    exclude:
      - .git/**
      - .git
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
    when: always
    expire_in: 2 weeks
  timeout: 8h
  needs: []

build_vanilla_ons:
  stage: bitfile
  extends: .common
  script:
    - make -f makefile.esnet vanilla_bitfile
  artifacts:
    name: "artifacts.vanilla.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - vanilla_artifact
    exclude:
      - .git/**
      - .git
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
    when: always
    expire_in: 2 weeks
  timeout: 8h
  needs: []
  rules:
    - when: manual


export_hwapi:
  stage: package
  extends: .common
  before_script: []
  script:
    - unzip examples/p4_simple/artifacts/open-nic-ci/artifacts.esnet-smartnic-hw.export_hwapi.0.zip
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - esnet-smartnic-hwapi
    when: always
    expire_in: 3 month
  timeout: 30m
  needs:
    - build_p4_simple

trigger_downstream_job:
  stage: trigger_downstream
  trigger:
    project: ht/esnet-smartnic-ht
    branch: main
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
