# versal_build.mk
#
# Reusable Makefile include for Versal shell/core assembly builds.
#
# Orchestrates the full Versal build by:
#   1. Generating a local build/src/ library with smartnic as a sub-library
#      (configure target)
#   2. Delegating assembly to scripts/shell_build.mk with Versal-specific
#      configuration (constraints, hooks, IP repos, device_image/xsa stages)
#   3. Adding the firmware PDI generation step on top (versal_pdi)
#
# Required input (must be set by the including Makefile before the include):
#   SMARTNIC_ROOT  - absolute path to the esnet-smartnic-hw repo root
#
# Optional overrides:
#   BOARD     - target board name (default: av80)
#   CORE      - core component reference, e.g. core.stub (default: core.stub)
#   BUILD_DIR - root build directory    (default: $(CURDIR)/build)
#
# Public targets provided:
#   versal_shell_ooc  - shell OOC synthesis (subcomponent of versal_design)
#   versal_core_ooc   - core OOC synthesis  (subcomponent of versal_design)
#   versal_design     - full-device link + implementation through XSA
#   versal_pdi        - versal_design + firmware PDI generation
#   versal_clean      - remove $(BUILD_DIR) entirely

# -----------------------------------------------
# Defaults
# -----------------------------------------------
BOARD     ?= av80
CORE      ?= core.stub
BUILD_DIR ?= $(CURDIR)/build

# -----------------------------------------------
# Paths
#
# Include only esnet-fpga-library/paths.mk (for SCRIPTS_ROOT) here.
# The full config chain is set up below for the assembly step.
# -----------------------------------------------
__VB_LIB_ROOT := $(SMARTNIC_ROOT)/esnet-fpga-library
include $(__VB_LIB_ROOT)/paths.mk

# Vivado version (same derivation as proj_config_base.mk)
XILINX_VIVADO__VERSION := $(firstword $(sort $(subst /, ,$(XILINX_VIVADO))))

BUILD_ID ?= $(shell date +"%s")

# -----------------------------------------------
# Derived paths
# -----------------------------------------------
__VB_BUILD_SRC_DIR  := $(BUILD_DIR)/src
__VB_BUILD_OUT_DIR  := $(BUILD_DIR)/out

# -----------------------------------------------
# Configure sentinel
# -----------------------------------------------
__VB_CONFIGURED := $(__VB_BUILD_SRC_DIR)/.configured

# -----------------------------------------------
# Configure target
#
# Generates the build/src library tree following the same echo+sed
# pattern as _configure_app_src_lib in scripts/app_config.mk.
#
# build/config.mk sets OUTPUT_ROOT__LOCAL *before* including the root
# config.mk so that ?= assignments don't override it.
# -----------------------------------------------
$(__VB_CONFIGURED): | $(__VB_BUILD_SRC_DIR)
	@echo "Configuring Versal build at $(BUILD_DIR) ..."
	@# --- build/config.mk ---
	@echo "# Autogenerated by versal_build.mk — do not edit"  >  $(BUILD_DIR)/config.mk
	@echo "SMARTNIC_ROOT      := $(abspath $(SMARTNIC_ROOT))" >> $(BUILD_DIR)/config.mk
	@echo "CFG_ROOT__LOCAL    := $(abspath $(SMARTNIC_ROOT))/cfg" >> $(BUILD_DIR)/config.mk
	@echo "OUTPUT_ROOT__LOCAL := $(abspath $(__VB_BUILD_OUT_DIR))" >> $(BUILD_DIR)/config.mk
	@echo "PROJ_ROOT          := $(abspath $(SMARTNIC_ROOT))" >> $(BUILD_DIR)/config.mk
	@echo "include \$$(SMARTNIC_ROOT)/config.mk"              >> $(BUILD_DIR)/config.mk
	@# --- build/src/Makefile ---
	@cp $(SCRIPTS_ROOT)/Makefiles/templates/lib.mk $(__VB_BUILD_SRC_DIR)/Makefile
	@# --- build/src/config.mk ---
	@cp $(SCRIPTS_ROOT)/Makefiles/templates/lib_config.mk $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<path-to-proj-root>|$(abspath $(BUILD_DIR))|'           $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<library-name>|ESnet SmartNIC Versal Build|'            $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<library-desc>|Versal shell build library|'             $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<libraries>|smartnic=$(abspath $(SMARTNIC_ROOT))/src|'  $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<common-lib-name>|common@smartnic|'                     $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<custom-env-setup>|BOARD ?= av80|'                      $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<output-subdir>|$$(BOARD)/$$(XILINX_VIVADO__VERSION)|'  $(__VB_BUILD_SRC_DIR)/config.mk
	@sed -i 's|<lib-env>|\\\n\tBOARD=$$(BOARD)|g'                     $(__VB_BUILD_SRC_DIR)/config.mk
	@touch $@
	@echo "Done."

$(__VB_BUILD_SRC_DIR):
	@mkdir -p $@

configure: $(__VB_CONFIGURED)
.PHONY: configure

# -----------------------------------------------
# Project config chain for the assembly step
#
# Setting OUTPUT_ROOT__LOCAL and CFG_ROOT__LOCAL before including config.mk
# ensures the ?= guards don't override them.
# -----------------------------------------------
__VB_SMARTNIC_ROOT     := $(abspath $(SMARTNIC_ROOT))
OUTPUT_ROOT__LOCAL     := $(abspath $(__VB_BUILD_OUT_DIR))
CFG_ROOT__LOCAL        := $(__VB_SMARTNIC_ROOT)/cfg
PROJ_ROOT              := $(__VB_SMARTNIC_ROOT)

include $(__VB_SMARTNIC_ROOT)/config.mk

# Derive LIB_OUTPUT_ROOT — mirrors what src/config.mk + lib_config_base.mk
# would compute, but we set it directly since we are not going through
# src/config.mk (which is the smartnic sub-library's config, not ours).
LIB_OUTPUT_ROOT := $(abspath $(__VB_BUILD_OUT_DIR)/$(BOARD)/$(XILINX_VIVADO__VERSION))

# component_funcs.mk provides get_lib_component_out_path_from_ref,
# needed by shell_build.mk to locate the shell and core DCPs.
include $(SCRIPTS_ROOT)/Makefiles/component_funcs.mk

# -----------------------------------------------
# shell_build.mk inputs
# -----------------------------------------------
__VB_TOP              := esnet_smartnic
__VB_AVED_BASE_DESIGN := amd_v80_gen5x8_25.1
__VB_SHELL_BOARD_DIR  := $(__VB_SMARTNIC_ROOT)/src/xilinx/alveo/versal/shell/$(BOARD)

SHELL_BUILD_REF   := xilinx.alveo.versal.shell.$(BOARD).build@smartnic
CORE_BUILD_REF    := $(CORE).build@smartnic
COMPONENT_OUT_PATH := $(__VB_BUILD_OUT_DIR)/$(BOARD)/$(XILINX_VIVADO__VERSION)/design/build

TOP := $(__VB_TOP)

CONSTRAINTS_XDC_IMPL := \
    $(abspath $(__VB_SHELL_BOARD_DIR)/impl.pins.xdc) \
    $(abspath $(__VB_SHELL_BOARD_DIR)/impl.xdc)

IMPL_HOOK_TCL_FILES := $(abspath $(wildcard $(__VB_SHELL_BOARD_DIR)/*.tcl))

IP_REPO_PATHS := \
    $(abspath $(__VB_SMARTNIC_ROOT)/src/xilinx/aved/hw/$(__VB_AVED_BASE_DESIGN)/src/iprepo)

# Extend default BUILD_STAGES with Versal-specific device output stages
BUILD_STAGES := link opt place place_opt route route_opt device_image xsa

# -----------------------------------------------
# Include generic assembly
# -----------------------------------------------
include $(__VB_SMARTNIC_ROOT)/scripts/Makefiles/shell_build_base.mk

# -----------------------------------------------
# Convenience OOC targets
#
# These allow building just the shell or core DCP without running the full
# assembly.  They dispatch through build/src/ using the same library dispatch
# that _pre_synth uses, so outputs land in the same locations.
# -----------------------------------------------
__VB_BUILD_ENV := BOARD=$(BOARD) BUILD_ID=$(BUILD_ID)

versal_shell_ooc: | $(__VB_CONFIGURED)
	@echo "Building Versal shell OOC DCP (BOARD=$(BOARD), $(BUILD_ID))..."
	@$(MAKE) -s -C $(__VB_BUILD_SRC_DIR) synth \
	    COMPONENT=$(SHELL_BUILD_REF) $(__VB_BUILD_ENV)
	@echo "Done."

versal_core_ooc: | $(__VB_CONFIGURED)
	@echo "Building Versal core OOC DCP (CORE=$(CORE), $(BUILD_ID))..."
	@$(MAKE) -s -C $(__VB_BUILD_SRC_DIR) synth \
	    COMPONENT=$(CORE_BUILD_REF) $(__VB_BUILD_ENV)
	@echo "Done."

.PHONY: versal_shell_ooc versal_core_ooc

# -----------------------------------------------
# versal_design
# -----------------------------------------------
versal_design: | $(__VB_CONFIGURED)
	@$(MAKE) -s shell_build BUILD_ID=$(BUILD_ID)

.PHONY: versal_design

# -----------------------------------------------
# versal_pdi
# -----------------------------------------------
__VB_PDI_SCRIPT  := $(__VB_SMARTNIC_ROOT)/scripts/versal/build_pdi.sh
__VB_PDI_HW_FILE := $(COMPONENT_OUT_PATH)/$(__VB_TOP).pdi
__VB_XSA_FILE    := $(COMPONENT_OUT_PATH)/$(__VB_TOP).xsa
__VB_PDI_APP     := $(COMPONENT_OUT_PATH)/$(__VB_TOP)_app.pdi

$(__VB_PDI_APP): $(__VB_PDI_HW_FILE) $(__VB_XSA_FILE)
	@$(__VB_PDI_SCRIPT) \
	    -p $(abspath $(__VB_SMARTNIC_ROOT)) \
	    -o $(COMPONENT_OUT_PATH) \
	    -d $(__VB_AVED_BASE_DESIGN) \
	    -t $(__VB_TOP)

versal_pdi: | $(__VB_CONFIGURED)
	@$(MAKE) -s shell_build BUILD_ID=$(BUILD_ID)
	@$(MAKE) -s $(__VB_PDI_APP) BUILD_ID=$(BUILD_ID)

.PHONY: versal_pdi

# -----------------------------------------------
# versal_clean
# -----------------------------------------------
versal_clean:
	@echo "Cleaning Versal build at $(BUILD_DIR) ..."
	@rm -rf $(BUILD_DIR)
	@echo "Done."

.PHONY: versal_clean
