# -----------------------------------------------
# Configuration
# -----------------------------------------------
REGRESSION = 0
SEED ?= 0
waves ?= OFF

# ----------------------------------------------------
# Defines / plusargs / options
# ----------------------------------------------------
override DEFINES +=
override PLUSARGS +=

COMPILE_OPTS =
ELAB_OPTS =
SIM_OPTS =

SUBCOMPONENTS = \
    xilinx.alveo.versal.bd \
    xilinx.alveo.versal.shell.rtl \
    core.stub.rtl

# -----------------------------------------------
# Use common testcase Makefile
# -----------------------------------------------
include ../test_base.mk
