# -----------------------------------------------
# Path setup
# -----------------------------------------------
IP_ROOT := .

# -----------------------------------------------
# IP config
# -----------------------------------------------
include $(IP_ROOT)/config.mk

# -----------------------------------------------
# VitisNetP4 IP config
# -----------------------------------------------
#VITISNETP4_IP_NAME = sdnet_egr

export P4_FILE := $(abspath $(IP_ROOT)/p4/p4_egr.p4)
#P4_OPTS ?= CONFIG.PKT_RATE {150} CONFIG.OUTPUT_METADATA_FOR_DROPPED_PKTS {true}
#EXAMPLE_TEST_DIR := $(IP_ROOT)/p4/sim/test-fwd-p0
#EXTERN_PORTS ?= False

#VITISNETP4_WRAPPER_FILE = $(IP_OUT_DIR)/$(VITISNETP4_IP_NAME)/$(VITISNETP4_IP_NAME)_wrapper.sv

# ----------------------------------------------------
# Targets
# ----------------------------------------------------
example:
	@$(MAKE) -C $(APP_DIR) example

.PHONY: example
