# ----------------------------------------------------
# App configuration defaults
# ----------------------------------------------------
# Intended to be included by 'parent' Makefile, with
# following variables defined:
#
# APP_DIR - absolute path to application directory
# SMARTNIC_DIR - absolute path to smartnic root directory

# Application Verilog source root directory
# ----------------------------------------------------
# if APP_DIR contains app_if/ subdir i.e. APP contains P4 + verilog, set APP_ROOT to APP_DIR,
# else APP is P4 file only, set APP_ROOT to p4_app (to get common P4 core verilog) and P4_FILE.
ifneq ($(wildcard $(APP_DIR)/app_if/.),)
APP_ROOT := $(APP_DIR)
else
APP_ROOT := $(PROJ_ROOT)/src/p4_app
endif

# App name
# ----------------------------------------------------
# Where APP_NAME is not set explicitly by parent (calling)
# Makefile, set APP_NAME to name of application root directory
APP_NAME_DEFAULT := $(notdir $(abspath $(APP_DIR)))
APP_NAME ?= $(shell echo $(APP_NAME_DEFAULT) | tr '[:upper:]' '[:lower:]')

# P4 file
# ----------------------------------------------------
# Full pathname of application p4 file
P4_FILE_DEFAULT := $(APP_DIR)/p4/$(APP_NAME).p4 
P4_FILE ?= $(P4_FILE_DEFAULT)

# P4 options
# ----------------------------------------------------
# Options to pass to p4 compiler
P4_OPTS_DEFAULT := CONFIG.PKT_RATE {150} \
                   CONFIG.OUTPUT_METADATA_FOR_DROPPED_PKTS {true}

P4_OPTS ?= $(P4_OPTS_DEFAULT)

# Build name
# ----------------------------------------------------
# Specify name of build and build artifacts
BUILD_NAME_DEFAULT := esnet-smartnic-$(APP_NAME)
BUILD_NAME ?= $(BUILD_NAME_DEFAULT)


# (Build) artifacts
# ----------------------------------------------------
# Set path for build artifacts (output) directory
ARTIFACTS_DIR_DEFAULT := $(APP_DIR)/artifacts
ARTIFACTS_DIR ?= $(ARTIFACTS_DIR_DEFAULT)

# Print parameters
# - convenience function for implementing targets that
#   echo the application parameters for reporting or
#   debug purposes
# ----------------------------------------------------
_print_app_config := \
    @echo "=============================================="; \
	 echo "Configuring application '$(APP_NAME)':"; \
     echo "=============================================="; \
     echo "APP_DIR      : $(APP_DIR)"; \
     echo "APP_NAME     : $(APP_NAME)"; \
     echo "APP_ROOT     : $(APP_ROOT)"; \
     echo "P4_FILE      : $(P4_FILE)"; \
     echo "P4_OPTS      : $(P4_OPTS)"; \
     echo "BUILD_NAME   : $(BUILD_NAME)"; \
     echo "ARTIFACTS_DIR: $(ARTIFACTS_DIR)"

# Write config to file
# - write application configuration to a file
# ----------------------------------------------------
APP_CFG_FILE := $(APP_DIR)/.app_config.mk

_write_app_config := \
    @echo "\#==============================================" >  $(APP_CFG_FILE); \
     echo "\# Application configuration"                     >> $(APP_CFG_FILE); \
     echo "\#"                                               >> $(APP_CFG_FILE); \
     echo "\# NOTE: This file is autogenerated."             >> $(APP_CFG_FILE); \
     echo "\#==============================================" >> $(APP_CFG_FILE); \
     echo "export APP_DIR := $(APP_DIR)"                     >> $(APP_CFG_FILE); \
     echo "APP_NAME       := $(APP_NAME)"                    >> $(APP_CFG_FILE); \
     echo "APP_ROOT       := $(APP_ROOT)"                    >> $(APP_CFG_FILE); \
     echo "P4_FILE        := $(P4_FILE)"                     >> $(APP_CFG_FILE); \
     echo "P4_OPTS        := $(P4_OPTS)"                     >> $(APP_CFG_FILE); \
     echo "BUILD_NAME     := $(BUILD_NAME)"                  >> $(APP_CFG_FILE); \
     echo "ARTIFACTS_DIR  := $(ARTIFACTS_DIR)"               >> $(APP_CFG_FILE)




